# Generated by Django 3.2.9 on 2021-11-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_circuit_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
