# Generated by Django 3.2.9 on 2021-11-21 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_circuit_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
