# Generated by Django 3.2.9 on 2021-11-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_circuit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='length',
            field=models.IntegerField(blank=True),
        ),
    ]
