# Generated by Django 3.2.9 on 2021-11-21 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playground', '0006_alter_circuit_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='length',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('weather', models.CharField(choices=[('R', 'Rainy'), ('S', 'Sunny'), ('C', 'Cloudy')], max_length=1)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.circuit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
