# Generated by Django 3.2.9 on 2021-11-21 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_followerlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
