# Generated by Django 3.2.9 on 2021-11-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_auto_20211121_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followerlist',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='followerlist',
            name='follows',
        ),
        migrations.RemoveField(
            model_name='followerlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lap',
            name='circuit',
        ),
        migrations.RemoveField(
            model_name='lap',
            name='user',
        ),
        migrations.DeleteModel(
            name='Circuit',
        ),
        migrations.DeleteModel(
            name='FollowerList',
        ),
        migrations.DeleteModel(
            name='Lap',
        ),
    ]
